### ISSUE TITLE
Simplify CSS for shared properties.

### ISSUE THREAD

**Issue by josephtkim** [OhLiverFun/prj-rev-bwfs-dasmoto#5]
It is a good idea to try and simplify the CSS code as much as you can to make the code cleaner and to remove repetitive code. There are several shared properties for multiple selectors in the CSS, which might make the code seem repetitive. Here is how you might simplify a few shared properties.

```css
.h1, h2, h3, .blue-highlight {
  font-family: Helvetica;
  font-weight: bold;
}

h2 {
  font-size: 26px;
  color: white;
}
```
